- Downgradeing to a lower transforemer version solved the error (github issue here https://github.com/huggingface/exporters/issues/42)
	- The models didn't pass all the checks, but the output looks close enough [[output](https://app.warp.dev/block/hJaku7BU2byK9DBjIYVwjd)]
	- The 2 pythia models (410m and 1b) are saved here: `/Users/kendreaditya/Documents/workspace/neural-engine-benchmark/latest-venv/mlmodels`
	- Used the same command: `python -m exporters.coreml --model=EleutherAI/pythia-1b-deduped mlmodels/pythia-1b-deduped-exported/`
	- Although the test fails when I try to test on IOS device